project:
  type: website
  render:
    - Day1_IRB25_part1.qmd
    - Day1_IRB25_part2.qmd
    - Day1_IRB25_part3.qmd
    - Day2_IRB25_part0.qmd
    - Day2_IRB25_part1.qmd
    - Day2_IRB25_plots.qmd
    - Day3_IRB25_part0.qmd
    - Introduction_to_stats_NEW.qmd
  output-dir: docs
website:
  title: "IRB workshop 2025"
  navbar:
    # logo: logo_KC.jpg
    right:
      - text: Day 1
        menu: 
          - text: Introduction to R
            href: Day1_IRB25_part1.qmd
          - text: Functions and conditions
            href: Day1_IRB25_part2.qmd
          - text: Regular expressions
            href: Day1_IRB25_part3.qmd
      - text: Day 2
        menu: 
          - text: Packages
            href: Day2_IRB25_part0.qmd
          - text: Table manipulation
            href: Day2_IRB25_part1.qmd
          - text: Visualization
            href: Day2_IRB25_plots.qmd
      - text: Day 3
        menu:
          - text: Practice
            href: Day3_IRB25_part0.qmd
          - text: Statistics
            href: Introduction_to_stats_NEW.qmd
      # - text: Day 4
      #   menu: 
      #     - text: Machine learning
      #       href: Introduction_to_ML.qmd
  page-footer:
    background: light
    left: "Copyright 2025"
    right: "This website is built with Quarto."
format:
  html:
    theme: styles.scss
    mainfont: Nunito
    toc: true
    page-layout: full
editor: visual
 # ðŸ‘‡ Add this line:
# resources:
#   - Projects/project_cancer/lung_cancer_subset_data.csv
#   - Projects/project_obesity/gut_obesity_subset.csv

